# Generated by Django 4.1.4 on 2022-12-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_expired_payments_payment_user_services_delete_pago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_user',
            old_name='service',
            new_name='service_id',
        ),
        migrations.RenameField(
            model_name='payment_user',
            old_name='user',
            new_name='user_id',
        ),
    ]
